name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: self-hosted

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
